# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idjango_practice', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artist',
            new_name='Artista',
        ),
        migrations.RenameField(
            model_name='artista',
            old_name='id_artist',
            new_name='id_artista',
        ),
        migrations.RenameField(
            model_name='artista',
            old_name='name_artist',
            new_name='name_artista',
        ),
    ]
