# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 09:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('idjango_practice', '0002_auto_20170421_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='idjango_practice.Artista'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artista',
            name='artista',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='playlist',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='idjango_practice.Song'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='song',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='idjango_practice.Album'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artista',
            name='id_artista',
            field=models.IntegerField(default=0),
        ),
    ]
