# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-26 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idjango_practice', '0002_auto_20170526_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='idjango_practice.Album'),
        ),
    ]
