# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-26 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idjango_practice', '0002_auto_20170526_1951'),
        ('idjango_practice', '0003_song_album'),
    ]

    operations = [
    ]
