# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-16 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idjango_practice', '0003_remove_artist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='url',
        ),
    ]
