# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-26 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idjango_practice', '0004_merge_20170526_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='url',
        ),
    ]
