# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-16 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idjango_practice', '0004_remove_artist_url'),
        ('idjango_practice', '0003_auto_20170616_1517'),
    ]

    operations = [
    ]
