# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-16 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idjango_practice', '0005_merge_20170616_1612'),
        ('idjango_practice', '0007_auto_20170616_1630'),
    ]

    operations = [
    ]
