# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-16 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idjango_practice', '0008_merge_20170616_1742'),
        ('idjango_practice', '0008_merge_20170616_1809'),
    ]

    operations = [
    ]
